export { default as Dashboard } from './Dashboard'
export { default as Payment } from './Payment'
export { default as Shopping } from './Shopping'
export { default as Orders } from './Orders'
export { default as Wishlist } from './Wishlist'
export { default as Settings } from './Settings'
export { default as Products } from './Products'